# Generated by Django 4.0.3 on 2022-04-02 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_products_options_alter_products_price_sliv'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='slivki',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Наличие на сливках'),
        ),
    ]
